### PR TITLE
[LOCAL-44] Strings: reverse sweep (auto)

### PR DESCRIPTION
**Pull request by string-sweep**
NOTE: String Sweep will be suspended for this repo until this PR is merged or closed!

/cc @zendesk/i18n @zendesk/i18n-dev
### Risks
Low. English edits and title improvements.

### CODE REVIEW

**Comment by dadah89** [comment]
You might want to give write access to zd engineering in this repo:
screen shot 2018-09-28 at 12 59 20 pm

**Comment by dadah89** [comment]
@ruthannedilig @fabioguarrasi could someone take a look at the conflict? thanks!

**Comment by ruthannedilig** [comment]
@dadah89 done! thanks!

**Comment by ruthannedilig** [comment]
@dadah89 done. thanks!

**Pull request merged**
